### ISSUE TITLE
Why not use ncurses fully?

### ISSUE THREAD

**Issue by livibetter** [Regaerd/PyClock#1]
I noticed the code updates clock through `stdout` not curses functions, since the library is used, why is it not used for updating?

There is related issue to that question, I have to do `sys.stdout.flush()` or the clock most of time wouldn't be printed out fully.

And another question, there seems no clearing, so every second, a new time is printed after the previous time, the screen is filled with those times, is this by design? Or you haven't got to do it?

**Comment by bdreager** [comment]
1) I don't have a lot of experience with the curses library, so I just went with what I knew. I'll look into switching the output from `stdout` to curses.

2) Surprisingly I haven't experienced this issue, but I see where the problem. I'll push a quick fix before working on curses.

3) The lack of clearing was by design, but I'm not really satisfied with it either. I'll be changing this pretty soon.

Thanks for the feedback!

**Comment by livibetter** [comment]
I see the e71c2bee7f83857c9a7a70aeb5c19cc2c61140d5. I hope you will continue, your clock is the only one can scale up and down text size. It has a good potential.

Closing since my questions are answered.
