### ISSUE TITLE
Move back to single threading

### ISSUE THREAD

**Issue by bdreager** [Regaerd/PyClock#8]
With controls and output both using curses, I can't tell if there's an advantage to using multiple threads anymore.

On the other hand, every thread uses extra memory; not much, but there's a definite benefit to reducing the number of threads.

http://stackoverflow.com/questions/5636660/why-does-python-thread-consume-so-much-memory

**Comment by livibetter** [comment]
I concur.

I don't really think it is necessary to use multi-thread for a clock, it's more like a _"Because I Can"_ thing. PyClock probably is the only clock that I know that utilizing threading, believe you me, I have seen at least [20 digital clocks](https://www.youtube.com/playlist?list=PLdvB7n7RN2UBAeDMTTyle1ekO_EZN2h6x) if not more, so far.

In reality, _KISS_ is the best approach and the most practical, IMHO.

Due to this upcoming change, I believe there would be a significant changes to the design, many stuff would be moved and re-shuffled around, so I will wait before getting onto #4.

**Comment by bdreager** [comment]
> believe you me, I have seen at least 20 digital clocks if not more, so far.

I didn't realize you were a terminal clock connoisseur. That makes sense looking back.

But yes, multithreading was an overdesign.

**Comment by bdreager** [comment]
dc9614189e7ebbae0d1ab0efb354604463b56d26

Update done. It was simpler than I thought.
